http:
  host: "0.0.0.0:20125"


mongodb:
  dsn:
  database: ""





kafka:
  host:
  topic: "report"
  key: "kafka:report:partition"
  start: 0
  end: 9




redis:
  address:
  password:
  db: 0

log:
  path: "/data/logs/collector-info.log"

management:
  address: